export var SpriteZMap = {
    world: 0,
    droppeditems: 8,
    droppeditemtext: 9,
    itemslots: 10,
    playerutility: 10,
    items: 11,
    playerutilityitems: 11,
    playerutilitygroup: 11,
    playerutilitytitle: 11,
    playerutilityitemimage: 11,
    playerutilitybutton: 11,
    playerutilityrequireditem: 11,
    itemtext: 12,
    elevateditems: 21,
    elevateditemtext: 22,
}
